### ISSUE TITLE
Yocto build automation for Boondocks OS

### ISSUE THREAD

**Issue by rquackenbush** [Boondocks/Boondocks#20]
This is running on my desktop for now. Let's get this moved to something awesomer. This seems too heavy duty for AppVeyor, but I could be wrong. Look at setting up a Linux agent for TeamCity.

**Comment by rquackenbush** [comment]
It's getting there. I have a nice script that cranks out a build, renames the image file and zips it up nicely. Just need to get this on a linux build agent.,

**Comment by rquackenbush** [comment]
This is on hold for the completion of this:
https://github.com/resin-os/meta-resin/pull/1028

**Comment by slimbrd** [comment]
- [ ] Prepare VM for `Yocto` builds.  Increase CPU and memory resources as appropriate.
- [ ] Prepare `bash` helper script to initiate build and handle perquisites, etc.
- [ ] Setup TeamCity build configuration to 'automate' final manual build actions.

`Yocto` builds now run on an internal TeamCity Linux instance.  The build process is kicked off locally on the VM using using a helper script wrapped in a `.bashrc` helper function called: `bos`.

The `bos.sh` helper script:
https://gist.github.com/boondocks-iot/457074c61698897fe75b8fd2a92ea290

`curl` wrapper to pull the helper `bos.sh` script and kick off a build:
https://gist.github.com/boondocks-iot/89a3b93784026ef6010b112259d3a04b

Once the `Yocto` build completes, the internal TeamCity instance has a build configuration setup that performs the following actions:

1. Prompt user for the Id of the Docker update image.  Example: `431f0bd02d9e`
2. Prompt the user for the OS version just built.  Example: `2.14.0-rev1`
3. Tag and push the Docker update image to [boondocks/boondocks-os](https://hub.docker.com/r/boondocks/boondocks-os/).
4. Import the newly built OS version into the Boondocks `HostVersions` table using the Boondocks Management API.

**Comment by slimbrd** [comment]
Yocto builds are now centralized and automated as much as is reasonable.
