### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [Boondocks/Boondocks#44]
Hello, I wanted to make a logo for this project and here's my proposal. If you like it I will send you all files. I'm waiting for your answer )

![b 2](https://user-images.githubusercontent.com/31902754/39492242-d8e1bca4-4d43-11e8-9e7a-76ee3ff0e266.png)

**Comment by slimbrd** [comment]
@tebriz159 We greatly appreciate you reaching out with a logo offer.  We had official logo images made a few weeks back.  Will close this issue.
