### ISSUE TITLE
Add PollInterval to device configuration.

### ISSUE THREAD

**Issue by rquackenbush** [Boondocks/Boondocks#89]
# Problem

The pollInterval is currently hardcoded to 60 at the management service level. This poses some problems:
- This could lead to scalability issues if this overwhelms our servers (each year we're adding at least 8,000 modules).
- Would be ideal to shorten the interval for development purposes so we spend less time waiting on the next heartbeat for something to take place.

# Solution

We should add this to the information that gets returned on the device api getConfiguration call.

Items:
- Add nullable `PollIntervalSeconds` to the `Devices` table. This will be the number of seconds in-between  heartbeat attempts.
- Add `PollIntervalSeconds` to the resource returned by the get device configuration call
- Make the agent use the value from the service (if available - i.e. is non null) when waiting between heartbeat attempts.

**Comment by grecosoft** [comment]
Completed.  Changes make to Boondocks.Device REST Api and to the Agent.
